import styles from "./blog.module.css";
import PostCard from "@/components/postCard/PostCard";
// import { getPosts } from "@/lib/data";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Blog List",
  description: "Generated by create next app",
};

const getData = async () => {
  const res = await fetch("http://localhost:3000/api/blog", {
    next: { revalidate: 3600 },
  });

  if (!res.ok) {
    throw new Error("Error fetch");
  }

  return res.json();
};

export default async function BlogPage() {
  const posts = await getData();

  return (
    <div className={styles.container}>
      {posts.map((post: any) => (
        <div className={styles.post} key={post.id}>
          <PostCard post={post} />
        </div>
      ))}
    </div>
  );
}
